org:
  nit:
    eid: 1006
    id-number:
      adhar: 836460037000
      pan: DOYP7678
      voter: 8956466586
    name: Tapas
    nick-name:
    - Tapas
    - Tapun
    - Bapun
    phone-number:
    - 999999999
    - 88888888
    - 77777777
    team-members:
    - Subha
    - Akash
    - Anu
    - Subha
